### ISSUE TITLE
Maquettage

### ISSUE THREAD

**Issue by Hikari-rom** [WhatToWatch-Groupe4/monorepo#21]
4 pages:

- Liste films
- Détail film
- Liste film vu et envie
- Liste commentaires

**Comment by agravelot** [comment]
![1 - Liste film - homepage](https://user-images.githubusercontent.com/13699253/108185343-7c118000-710c-11eb-9b69-35208a254a8b.png)
![2 - Liste film - homepage - scroll](https://user-images.githubusercontent.com/13699253/108185347-7d42ad00-710c-11eb-8b9d-5b80374a73a6.png)
![3 - Detail film](https://user-images.githubusercontent.com/13699253/108185349-7d42ad00-710c-11eb-8549-02e13ac57cc9.png)
![4 - Detail film + commentaires](https://user-images.githubusercontent.com/13699253/108185352-7ddb4380-710c-11eb-8c28-1ee1db9b17bd.png)

Voici les maquettes réalisées par @RomainFon

**Comment by agravelot** [comment]
@WhatToWatch-Groupe4/dev Tout vous semble bon ? :)

**Comment by Hikari-rom** [comment]
Pour moi c'est ok :)
